configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- ps: .\scripts\update-version.ps1
before_build:
- ps: nuget restore
build:
  project: SignalR.Client.Portable.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
nuget:
  project_feed: true
  disable_publish_on_pr: true
test:
  assemblies: '**\*.Tests.dll'
deploy:
- provider: NuGet
  api_key:
    secure: tGdmfvratYIxf1BjUhTaGbbbaSJjCq/G6c55mxgQQ5qUmu/Jfetzibf8uOKzqx9W
  on:
    appveyor_repo_tag: true